# vscode module
# mode      source              target                                                          os
symlink     settings.json       ~/.config/Code/User/settings.json                               os=linux
symlink     keybindings.json    ~/.config/Code/User/keybindings.json                            os=linux
symlink     settings.json       ~/Library/Application\ Support/Code/User/settings.json          os=mac
symlink     keybindings.json    ~/Library/Application\ Support/Code/User/keybindings.json       os=mac
